version: "3"
services:
  mysql:
    image: mysql:8.0.26
    platform: linux/x86_64
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
  grafana:
    image: mericodev/grafana:0.4.0
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_LIVE_ALLOWED_ORIGINS=*
    restart: always
    depends_on:
      - mysql
  devlake:
    image: mericodev/lake:0.4.0
    ports:
      - 127.0.0.1:8080:8080
    restart: always
    volumes:
      - ./.env:/app/.env
    depends_on:
      - grafana
    environment:
      WAIT_HOSTS: mysql:3306, grafana:3000   
  config-ui:
    #image: mericodev/config-ui:0.4.0
    build: 
      context: ./config-ui
    ports:
      - 127.0.0.1:4000:80
    env_file:
      - ./.env
    depends_on:
      - devlake
    environment:
      WAIT_HOSTS: mysql:3306, grafana:3000, devlake:8080
volumes:
  mysql-storage:
  grafana-storage:
